"""initialize waste_detect models

Revision ID: b938cea9606f
Revises: 
Create Date: 2026-06-19 15:41:34.460272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b938cea9606f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('Fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_Fullname'), ['Fullname'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('predicted_category', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifications_captured_at'), ['captured_at'], unique=False)

    op.create_table('monthly_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_sorted', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_user_monthly_stats')
    )
    op.create_table('low_confidence_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classification_id', sa.String(length=36), nullable=False),
    sa.Column('auto_generated_explanation', sa.Text(), nullable=True),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('low_confidence_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_low_confidence_audit_logs_reviewed_by_admin'), ['reviewed_by_admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('low_confidence_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_low_confidence_audit_logs_reviewed_by_admin'))

    op.drop_table('low_confidence_audit_logs')
    op.drop_table('monthly_stats')
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classifications_captured_at'))

    op.drop_table('classifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_Fullname'))

    op.drop_table('users')
    # ### end Alembic commands ###
